In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import time

In [2]:
df=pd.read_csv("F:\Work\diease detection\chronic-1.csv")

In [14]:
df['appet'].unique()

array(['good', 'poor', '?', 'no'], dtype=object)

In [4]:
df=df.replace('?',np.nan)

In [5]:
data=df[['sg', 'al', 'su', 'bgr', 'sc', 'hemo', 'pcv', 'rbcc', 'rbc', 'htn',
       'dm', 'appet','Label']].copy()

In [6]:
#df1=df.drop(columns=['id','age','bp','sg','al','su','bgr','bu','sc','sod','pot','hemo','pcv','wbcc','rbcc'])

In [7]:
df1=data.drop(columns=['rbc','htn','dm','appet','Label'])

In [8]:
df1

sg   al   su  bgr    sc  hemo  pcv rbcc
0     1.02    1    0  121   1.2  15.4   44  5.2
1     1.02    4    0  NaN   0.8  11.3   38  NaN
2     1.02    0    0   92   1.2  14.9   48  5.4
3     1.01    2    3  423   1.8   9.6   31  NaN
4    1.005    4    0  117   3.8  11.2   32  3.9
..     ...  ...  ...  ...   ...   ...  ...  ...
395   1.02    0    0   91   0.7    14   46  5.8
396  1.015    3    2  463   2.8  12.2   40  4.6
397    NaN  NaN  NaN  103   5.3   6.3   19  2.6
398  1.015    3    0  106  15.2   8.6   26  2.5
399   1.02    0    0  119   0.7   NaN  NaN  NaN

[400 rows x 8 columns]

In [9]:
from sklearn.linear_model import LinearRegression
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [10]:
lr=LinearRegression()
imp=IterativeImputer(estimator=lr,verbose=2,max_iter=100, tol=1e-10, imputation_order='roman')

In [11]:
df2=imp.fit_transform(df1)

[IterativeImputer] Completing matrix with shape (400, 8)
[IterativeImputer] Ending imputation round 1/100, elapsed time 0.03
[IterativeImputer] Change: 182.27250463282854, scaled tolerance: 4.9e-08 
[IterativeImputer] Ending imputation round 2/100, elapsed time 0.05
[IterativeImputer] Change: 18.887880713989645, scaled tolerance: 4.9e-08 
[IterativeImputer] Ending imputation round 3/100, elapsed time 0.06
[IterativeImputer] Change: 15.664749386650769, scaled tolerance: 4.9e-08 
[IterativeImputer] Ending imputation round 4/100, elapsed time 0.07
[IterativeImputer] Change: 12.960883525118291, scaled tolerance: 4.9e-08 
[IterativeImputer] Ending imputation round 5/100, elapsed time 0.09
[IterativeImputer] Change: 10.635872032213825, scaled tolerance: 4.9e-08 
[IterativeImputer] Ending imputation round 6/100, elapsed time 0.11
[IterativeImputer] Change: 8.77827989097402, scaled tolerance: 4.9e-08 
[IterativeImputer] Ending imputation round 7/100, elapsed time 0.12
[IterativeImputer] Change

[IterativeImputer] Change: 0.0007850285416637348, scaled tolerance: 4.9e-08 
[IterativeImputer] Ending imputation round 66/100, elapsed time 0.95
[IterativeImputer] Change: 0.0006723837501489971, scaled tolerance: 4.9e-08 
[IterativeImputer] Ending imputation round 67/100, elapsed time 0.97
[IterativeImputer] Change: 0.0005759035460228823, scaled tolerance: 4.9e-08 
[IterativeImputer] Ending imputation round 68/100, elapsed time 0.99
[IterativeImputer] Change: 0.0004932680460778549, scaled tolerance: 4.9e-08 
[IterativeImputer] Ending imputation round 69/100, elapsed time 1.01
[IterativeImputer] Change: 0.00042249037461350447, scaled tolerance: 4.9e-08 
[IterativeImputer] Ending imputation round 70/100, elapsed time 1.03
[IterativeImputer] Change: 0.00036186884295719146, scaled tolerance: 4.9e-08 
[IterativeImputer] Ending imputation round 71/100, elapsed time 1.04
[IterativeImputer] Change: 0.00030994599941336354, scaled tolerance: 4.9e-08 
[IterativeImputer] Ending imputation round 7

C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\sklearn\impute\_iterative.py:685: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn("[IterativeImputer] Early stopping criterion not"


In [12]:
dl1=pd.DataFrame(df2,columns=('sg','al','su','bgr','sc','hemo','pcv','rbcc'))

In [13]:
dl1.head(20)

sg   al   su         bgr    sc  hemo   pcv      rbcc
0   1.020  1.0  0.0  121.000000   1.2  15.4  44.0  5.200000
1   1.020  4.0  0.0  155.893755   0.8  11.3  38.0  4.483714
2   1.020  0.0  0.0   92.000000   1.2  14.9  48.0  5.400000
3   1.010  2.0  3.0  423.000000   1.8   9.6  31.0  3.742738
4   1.005  4.0  0.0  117.000000   3.8  11.2  32.0  3.900000
5   1.020  0.0  0.0   89.000000   0.5  16.7  52.0  5.000000
6   1.010  2.0  0.0  106.000000   1.4  11.6  35.0  4.600000
7   1.015  3.0  0.0   74.000000   1.1  12.2  39.0  4.400000
8   1.025  0.0  0.0  124.000000   1.0  14.9  41.0  5.700000
9   1.020  0.0  0.0  110.000000   0.7  14.3  40.0  5.800000
10  1.020  0.0  0.0  122.000000   0.8  17.1  41.0  5.200000
11  1.020  2.0  0.0   70.000000   7.2   9.5  29.0  3.700000
12  1.010  2.0  4.0  490.000000   4.0   9.4  28.0  3.561102
13  1.020  0.0  0.0  128.000000   1.2  15.2  52.0  5.700000
14  1.020  0.0  0.0  137.000000   0.5  13.6  44.0  4.500000
15  1.020  0.0  0.0  102.000000   0.7  13.2  44.0  5.400000
16  1.025  0.0  0.0  132.000000   1.1  13.7  45.0  5.600000
17  1.010  0.0  0.0  100.000000  24.0  12.4  36.0  4.152490
18  1.015  2.0  4.0  410.000000   1.1  12.4  44.0  5.000000
19  1.025  0.0  0.0   75.000000   0.8  16.8  51.0  6.500000

In [14]:
df3=data.drop(columns=['sg','al','su','bgr','sc','hemo','pcv','rbcc','Label'])

In [15]:
df3

rbc  htn   dm appet
0         NaN  yes  yes  good
1         NaN   no   no  good
2      normal   no   no  good
3      normal   no  yes  poor
4      normal  yes   no  poor
..        ...  ...  ...   ...
395    normal   no   no  good
396       NaN  yes  yes  good
397       NaN  yes   no  poor
398  abnormal  yes   no  good
399    normal   no   no  good

[400 rows x 4 columns]

In [16]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy='constant',fill_value='Missing')
df4=imputer.fit_transform(df3)

In [17]:
dl2=pd.DataFrame(df4,columns=('rbc','htn','dm','appet'))

In [18]:
dl2.head()

rbc  htn   dm appet
0  Missing  yes  yes  good
1  Missing   no   no  good
2   normal   no   no  good
3   normal   no  yes  poor
4   normal  yes   no  poor

In [19]:
from sklearn.preprocessing import OrdinalEncoder
ordi=OrdinalEncoder()

In [20]:
dl3=ordi.fit_transform(dl2)

In [21]:
dl4=pd.DataFrame(dl3,columns=('rbc','htn','dm','appet'))

In [22]:
dl4

rbc  htn   dm  appet
0    0.0  2.0  2.0    1.0
1    0.0  1.0  1.0    1.0
2    2.0  1.0  1.0    1.0
3    2.0  1.0  2.0    3.0
4    2.0  2.0  1.0    3.0
..   ...  ...  ...    ...
395  2.0  1.0  1.0    1.0
396  0.0  2.0  2.0    1.0
397  0.0  2.0  1.0    3.0
398  1.0  2.0  1.0    1.0
399  2.0  1.0  1.0    1.0

[400 rows x 4 columns]

In [23]:
x=pd.concat([dl1,dl4],axis=1)

In [24]:
x

sg        al        su         bgr    sc      hemo        pcv  \
0    1.020000  1.000000  0.000000  121.000000   1.2  15.40000  44.000000   
1    1.020000  4.000000  0.000000  155.893755   0.8  11.30000  38.000000   
2    1.020000  0.000000  0.000000   92.000000   1.2  14.90000  48.000000   
3    1.010000  2.000000  3.000000  423.000000   1.8   9.60000  31.000000   
4    1.005000  4.000000  0.000000  117.000000   3.8  11.20000  32.000000   
..        ...       ...       ...         ...   ...       ...        ...   
395  1.020000  0.000000  0.000000   91.000000   0.7  14.00000  46.000000   
396  1.015000  3.000000  2.000000  463.000000   2.8  12.20000  40.000000   
397  1.010512  2.699747 -0.255426  103.000000   5.3   6.30000  19.000000   
398  1.015000  3.000000  0.000000  106.000000  15.2   8.60000  26.000000   
399  1.020000  0.000000  0.000000  119.000000   0.7  14.11269  43.142595   

         rbcc  rbc  htn   dm  appet  
0    5.200000  0.0  2.0  2.0    1.0  
1    4.483714  0.0  1.0  1.0    1.0  
2    5.400000  2.0  1.0  1.0    1.0  
3    3.742738  2.0  1.0  2.0    3.0  
4    3.900000  2.0  2.0  1.0    3.0  
..        ...  ...  ...  ...    ...  
395  5.800000  2.0  1.0  1.0    1.0  
396  4.600000  0.0  2.0  2.0    1.0  
397  2.600000  0.0  2.0  1.0    3.0  
398  2.500000  1.0  2.0  1.0    1.0  
399  5.029438  2.0  1.0  1.0    1.0  

[400 rows x 12 columns]

In [25]:
y=df['Label']

In [26]:
a=pd.concat([x,y],axis=1)

In [27]:
a

sg        al        su         bgr    sc      hemo        pcv  \
0    1.020000  1.000000  0.000000  121.000000   1.2  15.40000  44.000000   
1    1.020000  4.000000  0.000000  155.893755   0.8  11.30000  38.000000   
2    1.020000  0.000000  0.000000   92.000000   1.2  14.90000  48.000000   
3    1.010000  2.000000  3.000000  423.000000   1.8   9.60000  31.000000   
4    1.005000  4.000000  0.000000  117.000000   3.8  11.20000  32.000000   
..        ...       ...       ...         ...   ...       ...        ...   
395  1.020000  0.000000  0.000000   91.000000   0.7  14.00000  46.000000   
396  1.015000  3.000000  2.000000  463.000000   2.8  12.20000  40.000000   
397  1.010512  2.699747 -0.255426  103.000000   5.3   6.30000  19.000000   
398  1.015000  3.000000  0.000000  106.000000  15.2   8.60000  26.000000   
399  1.020000  0.000000  0.000000  119.000000   0.7  14.11269  43.142595   

         rbcc  rbc  htn   dm  appet   Label  
0    5.200000  0.0  2.0  2.0    1.0     ckd  
1    4.483714  0.0  1.0  1.0    1.0     ckd  
2    5.400000  2.0  1.0  1.0    1.0  notckd  
3    3.742738  2.0  1.0  2.0    3.0     ckd  
4    3.900000  2.0  2.0  1.0    3.0     ckd  
..        ...  ...  ...  ...    ...     ...  
395  5.800000  2.0  1.0  1.0    1.0  notckd  
396  4.600000  0.0  2.0  2.0    1.0     ckd  
397  2.600000  0.0  2.0  1.0    3.0     ckd  
398  2.500000  1.0  2.0  1.0    1.0     ckd  
399  5.029438  2.0  1.0  1.0    1.0  notckd  

[400 rows x 13 columns]

In [28]:
#a=a.sort_values(['bu'],ascending=False)
#a.reset_index(drop=True,inplace=True)

In [29]:
#a.tail(40)

In [30]:
Label={'notckd':0,'ckd':1}
a['Label']=a['Label'].map(Label)

In [31]:
a.head(20)

sg   al   su         bgr    sc  hemo   pcv      rbcc  rbc  htn   dm  \
0   1.020  1.0  0.0  121.000000   1.2  15.4  44.0  5.200000  0.0  2.0  2.0   
1   1.020  4.0  0.0  155.893755   0.8  11.3  38.0  4.483714  0.0  1.0  1.0   
2   1.020  0.0  0.0   92.000000   1.2  14.9  48.0  5.400000  2.0  1.0  1.0   
3   1.010  2.0  3.0  423.000000   1.8   9.6  31.0  3.742738  2.0  1.0  2.0   
4   1.005  4.0  0.0  117.000000   3.8  11.2  32.0  3.900000  2.0  2.0  1.0   
5   1.020  0.0  0.0   89.000000   0.5  16.7  52.0  5.000000  2.0  1.0  1.0   
6   1.010  2.0  0.0  106.000000   1.4  11.6  35.0  4.600000  2.0  1.0  1.0   
7   1.015  3.0  0.0   74.000000   1.1  12.2  39.0  4.400000  0.0  2.0  2.0   
8   1.025  0.0  0.0  124.000000   1.0  14.9  41.0  5.700000  2.0  1.0  1.0   
9   1.020  0.0  0.0  110.000000   0.7  14.3  40.0  5.800000  2.0  1.0  1.0   
10  1.020  0.0  0.0  122.000000   0.8  17.1  41.0  5.200000  2.0  1.0  1.0   
11  1.020  2.0  0.0   70.000000   7.2   9.5  29.0  3.700000  1.0  2.0  2.0   
12  1.010  2.0  4.0  490.000000   4.0   9.4  28.0  3.561102  0.0  2.0  2.0   
13  1.020  0.0  0.0  128.000000   1.2  15.2  52.0  5.700000  2.0  1.0  1.0   
14  1.020  0.0  0.0  137.000000   0.5  13.6  44.0  4.500000  2.0  1.0  1.0   
15  1.020  0.0  0.0  102.000000   0.7  13.2  44.0  5.400000  2.0  1.0  1.0   
16  1.025  0.0  0.0  132.000000   1.1  13.7  45.0  5.600000  2.0  1.0  1.0   
17  1.010  0.0  0.0  100.000000  24.0  12.4  36.0  4.152490  0.0  1.0  1.0   
18  1.015  2.0  4.0  410.000000   1.1  12.4  44.0  5.000000  2.0  1.0  2.0   
19  1.025  0.0  0.0   75.000000   0.8  16.8  51.0  6.500000  2.0  1.0  1.0   

    appet  Label  
0     1.0      1  
1     1.0      1  
2     1.0      0  
3     3.0      1  
4     3.0      1  
5     1.0      0  
6     1.0      1  
7     1.0      1  
8     1.0      0  
9     0.0      0  
10    1.0      0  
11    3.0      1  
12    1.0      1  
13    1.0      0  
14    1.0      0  
15    1.0      0  
16    1.0      0  
17    1.0      1  
18    1.0      1  
19    1.0      0

In [32]:
u=a.iloc[:,:-1]
v=a['Label']

In [33]:
from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import SVMSMOTE 

In [34]:
smote=SMOTE()
sm = SVMSMOTE()

In [35]:
x_train_resample,y_train_resample=sm.fit_resample(u,v) 

In [36]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
k=scaler.fit_transform(x_train_resample)

In [37]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(k,y_train_resample,test_size=0.2, random_state=0)

In [38]:
from sklearn.model_selection import KFold
from sklearn.model_selection import ShuffleSplit
fold=ShuffleSplit(n_splits=5, test_size=0.1, random_state=0)
fold1=KFold(5)
from sklearn.model_selection import cross_val_score

In [39]:
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [40]:
svm=SVC(C=0.1)
knn=KNeighborsClassifier(n_neighbors=7,weights= 'uniform',metric='minkowski')
gdb=GradientBoostingClassifier(n_estimators=500,max_depth=8,learning_rate=0.1,min_samples_leaf=8)
lgb=LGBMClassifier(n_estimators=200,max_depth=7,learning_rate=0.05,min_child_weight=1)
xgb=XGBClassifier(n_estimators=700,max_depth=4,learning_rate=0.05,min_child_weight=1,eval_metric='error')

In [41]:
labels=['svm','knn','gdb','xgb','lgb']

In [42]:
for clf,label in zip([svm,knn,gdb,xgb,lgb],labels):
    training_start = time.perf_counter()
    results_svm=cross_val_score(clf,x_train,y_train,cv=fold,scoring='accuracy')
    training_end = time.perf_counter()
    train_time = training_end-training_start
    print("Time consumed for training: %4.3f seconds" % (train_time))
    print("%0.4faccuracy with a standard deviation of %0.4f" % (results_svm.mean(), results_svm.std()),label)

Time consumed for training: 0.044 seconds
1.0000accuracy with a standard deviation of 0.0000 svm
Time consumed for training: 0.036 seconds
1.0000accuracy with a standard deviation of 0.0000 knn
Time consumed for training: 7.610 seconds
0.9900accuracy with a standard deviation of 0.0122 gdb


C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgbo

Time consumed for training: 2.301 seconds
0.9850accuracy with a standard deviation of 0.0122 xgb
Time consumed for training: 0.472 seconds
0.9950accuracy with a standard deviation of 0.0100 lgb


In [43]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score 

In [44]:
for clf,label in zip([svm,knn,gdb,xgb,lgb],labels):
    training_start = time.perf_counter()
    clf.fit(x_train,y_train)
    training_end = time.perf_counter()
    train_time = training_end-training_start
    print("Time consumed for training: %4.3f seconds" % (train_time))
    y_pred=clf.predict(x_test)
    print(accuracy_score(y_test,y_pred),label)
    print(confusion_matrix(y_test,y_pred))
    print(precision_score(y_test,y_pred))
    print(recall_score(y_test,y_pred))
    print(f1_score(y_test,y_pred))
    print(roc_auc_score(y_test,y_pred))
        

Time consumed for training: 0.013 seconds
1.0 svm
[[45  0]
 [ 0 55]]
1.0
1.0
1.0
1.0
Time consumed for training: 0.004 seconds
1.0 knn
[[45  0]
 [ 0 55]]
1.0
1.0
1.0
1.0
Time consumed for training: 1.847 seconds
1.0 gdb
[[45  0]
 [ 0 55]]
1.0
1.0
1.0
1.0


C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


Time consumed for training: 0.505 seconds
1.0 xgb
[[45  0]
 [ 0 55]]
1.0
1.0
1.0
1.0
Time consumed for training: 0.093 seconds
1.0 lgb
[[45  0]
 [ 0 55]]
1.0
1.0
1.0
1.0


In [45]:
from mlxtend.evaluate import combined_ftest_5x2cv

In [72]:
f, p = combined_ftest_5x2cv(estimator1=lgb,
                            estimator2=xgb,
                            X=k, y=y_train_resample,
                            random_seed=1)

C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgbo

In [73]:
print('F statistic: %.3f' % f)
print('p value: %.3f' % p)

F statistic: nan
p value: nan
