In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
import time

In [2]:
df=pd.read_csv("F:\Work\diease detection\chronic-1.csv")

In [3]:
df['sc'].unique()

array(['1.2', '0.8', '1.8', '3.8', '0.5', '1.4', '1.1', '1', '0.7', '7.2',
       '4', '24', '1.9', '2.7', '2.1', '4.6', '4.1', '0.9', '0.6', '5.2',
       '1.3', '9.6', '2.2', '1.6', '3.9', '76', '7.7', '?', '2.4', '1.5',
       '2.5', '7.3', '2', '3.4', '10.8', '6.3', '5.9', '3', '0.4', '3.25',
       '9.7', '32', '6.1', '6.4', '3.2', '3.3', '2.8', '6.7', '8.5', '15',
       '2.9', '1.7', '3.6', '5.6', '6.5', '4.4', '10.2', '11.5', '12.2',
       '5.3', '13.8', '9.2', '16.9', '6', '7.1', '18', '2.3', '13',
       '48.1', '14.2', '16.4', '7.5', '2.6', '4.3', '18.1', '11.8', '9.3',
       '6.8', '13.5', '12.8', '11.9', '12', '13.4', '13.3', '15.2'],
      dtype=object)

In [4]:
df=df.replace('?',np.nan)

In [5]:
data=df[['age','bp','sg','al','su','bgr','bu','sc','sod','pot','hemo','pcv','wbcc','rbcc',
         'rbc','pc','htn','dm','appet','pe','Label']].copy()

In [6]:
#df1=df.drop(columns=['id','age','bp','sg','al','su','bgr','bu','sc','sod','pot','hemo','pcv','wbcc','rbcc'])

In [7]:
df1=data.drop(columns=['rbc','pc','htn','dm','appet','pe','Label'])

In [8]:
df1

age   bp     sg   al   su  bgr   bu    sc  sod  pot  hemo  pcv  wbcc rbcc
0    48   80   1.02    1    0  121   36   1.2  NaN  NaN  15.4   44  7800  5.2
1     7   50   1.02    4    0  NaN   18   0.8  NaN  NaN  11.3   38  6000  NaN
2    50  NaN   1.02    0    0   92   19   1.2  150  4.8  14.9   48  4700  5.4
3    62   80   1.01    2    3  423   53   1.8  NaN  NaN   9.6   31  7500  NaN
4    48   70  1.005    4    0  117   56   3.8  111  2.5  11.2   32  6700  3.9
..   ..  ...    ...  ...  ...  ...  ...   ...  ...  ...   ...  ...   ...  ...
395  38   60   1.02    0    0   91   36   0.7  135  3.7    14   46  9100  5.8
396  64   90  1.015    3    2  463   64   2.8  135  4.1  12.2   40  9800  4.6
397  48  100    NaN  NaN  NaN  103   79   5.3  135  6.3   6.3   19  7200  2.6
398  48  110  1.015    3    0  106  215  15.2  120  5.7   8.6   26  5000  2.5
399  40   80   1.02    0    0  119   15   0.7  150  4.9   NaN  NaN   NaN  NaN

[400 rows x 14 columns]

In [9]:
from sklearn.linear_model import LinearRegression
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [10]:
lr=LinearRegression()
imp=IterativeImputer(estimator=lr,verbose=2,max_iter=100, tol=1e-10, imputation_order='roman')

In [11]:
df2=imp.fit_transform(df1)

[IterativeImputer] Completing matrix with shape (400, 14)
[IterativeImputer] Ending imputation round 1/100, elapsed time 0.08
[IterativeImputer] Change: 5240.18969198514, scaled tolerance: 2.64e-06 
[IterativeImputer] Ending imputation round 2/100, elapsed time 0.13
[IterativeImputer] Change: 653.8287601606843, scaled tolerance: 2.64e-06 
[IterativeImputer] Ending imputation round 3/100, elapsed time 0.17
[IterativeImputer] Change: 363.8180722043091, scaled tolerance: 2.64e-06 
[IterativeImputer] Ending imputation round 4/100, elapsed time 0.20
[IterativeImputer] Change: 167.7693491853986, scaled tolerance: 2.64e-06 
[IterativeImputer] Ending imputation round 5/100, elapsed time 0.25
[IterativeImputer] Change: 89.20450997791129, scaled tolerance: 2.64e-06 
[IterativeImputer] Ending imputation round 6/100, elapsed time 0.28
[IterativeImputer] Change: 63.27932177052491, scaled tolerance: 2.64e-06 
[IterativeImputer] Ending imputation round 7/100, elapsed time 0.31
[IterativeImputer] Chan

[IterativeImputer] Change: 0.000820695107466296, scaled tolerance: 2.64e-06 
[IterativeImputer] Ending imputation round 59/100, elapsed time 1.96
[IterativeImputer] Change: 0.0006731559304123946, scaled tolerance: 2.64e-06 
[IterativeImputer] Ending imputation round 60/100, elapsed time 1.99
[IterativeImputer] Change: 0.0005521703031410308, scaled tolerance: 2.64e-06 
[IterativeImputer] Ending imputation round 61/100, elapsed time 2.02
[IterativeImputer] Change: 0.00045293479430286165, scaled tolerance: 2.64e-06 
[IterativeImputer] Ending imputation round 62/100, elapsed time 2.04
[IterativeImputer] Change: 0.00037155186889170633, scaled tolerance: 2.64e-06 
[IterativeImputer] Ending imputation round 63/100, elapsed time 2.06
[IterativeImputer] Change: 0.00030481566554607653, scaled tolerance: 2.64e-06 
[IterativeImputer] Ending imputation round 64/100, elapsed time 2.09
[IterativeImputer] Change: 0.00025006776150937604, scaled tolerance: 2.64e-06 
[IterativeImputer] Ending imputation 

In [12]:
dl1=pd.DataFrame(df2,columns=('age','bp','sg','al','su','bgr','bu','sc','sod','pot','hemo','pcv','wbcc','rbcc'))

In [13]:
dl1.head(20)

age         bp     sg   al   su         bgr     bu    sc         sod  \
0   48.0  80.000000  1.020  1.0  0.0  121.000000   36.0   1.2  138.825303   
1    7.0  50.000000  1.020  4.0  0.0  152.129316   18.0   0.8  130.721286   
2   50.0  74.867666  1.020  0.0  0.0   92.000000   19.0   1.2  150.000000   
3   62.0  80.000000  1.010  2.0  3.0  423.000000   53.0   1.8  132.747426   
4   48.0  70.000000  1.005  4.0  0.0  117.000000   56.0   3.8  111.000000   
5   30.0  80.000000  1.020  0.0  0.0   89.000000   42.0   0.5  139.000000   
6   51.0  80.000000  1.010  2.0  0.0  106.000000   26.0   1.4  133.647830   
7   60.0  90.000000  1.015  3.0  0.0   74.000000   25.0   1.1  142.000000   
8   47.0  80.000000  1.025  0.0  0.0  124.000000   44.0   1.0  140.000000   
9   75.0  60.000000  1.020  0.0  0.0  110.000000   50.0   0.7  135.000000   
10  41.0  80.000000  1.020  0.0  0.0  122.000000   25.0   0.8  138.000000   
11  53.0  90.000000  1.020  2.0  0.0   70.000000  107.0   7.2  114.000000   
12  50.0  60.000000  1.010  2.0  4.0  490.000000   55.0   4.0  129.654816   
13  52.0  80.000000  1.020  0.0  0.0  128.000000   30.0   1.2  140.000000   
14  47.0  60.000000  1.020  0.0  0.0  137.000000   17.0   0.5  150.000000   
15  46.0  60.000000  1.020  0.0  0.0  102.000000   27.0   0.7  142.000000   
16  56.0  60.000000  1.025  0.0  0.0  132.000000   18.0   1.1  147.000000   
17  68.0  70.000000  1.010  0.0  0.0  100.000000   54.0  24.0  104.000000   
18  24.0  79.043223  1.015  2.0  4.0  410.000000   31.0   1.1  135.675311   
19  48.0  80.000000  1.025  0.0  0.0   75.000000   22.0   0.8  137.000000   

         pot  hemo   pcv          wbcc      rbcc  
0   3.818908  15.4  44.0   7800.000000  5.200000  
1   3.892231  11.3  38.0   6000.000000  4.684685  
2   4.800000  14.9  48.0   4700.000000  5.400000  
3   4.966038   9.6  31.0   7500.000000  3.737033  
4   2.500000  11.2  32.0   6700.000000  3.900000  
5   5.000000  16.7  52.0  10200.000000  5.000000  
6   3.406368  11.6  35.0   7300.000000  4.600000  
7   3.200000  12.2  39.0   7800.000000  4.400000  
8   4.900000  14.9  41.0   7000.000000  5.700000  
9   5.000000  14.3  40.0   8300.000000  5.800000  
10  5.000000  17.1  41.0   9100.000000  5.200000  
11  3.700000   9.5  29.0  12100.000000  3.700000  
12  5.303809   9.4  28.0  10101.651324  3.563175  
13  4.500000  15.2  52.0   4300.000000  5.700000  
14  3.500000  13.6  44.0   7900.000000  4.500000  
15  4.900000  13.2  44.0  11000.000000  5.400000  
16  4.700000  13.7  45.0   7500.000000  5.600000  
17  4.000000  12.4  36.0   5473.550467  4.174756  
18  5.506120  12.4  44.0   6900.000000  5.000000  
19  5.000000  16.8  51.0   6000.000000  6.500000

In [14]:
df3=data.drop(columns=['age','bp','sg','al','su','bgr','bu','sc','sod','pot','hemo','pcv','wbcc','rbcc','Label'])

In [15]:
df3

rbc        pc  htn   dm appet   pe
0         NaN    normal  yes  yes  good   no
1         NaN    normal   no   no  good   no
2      normal    normal   no   no  good   no
3      normal    normal   no  yes  poor   no
4      normal  abnormal  yes   no  poor  yes
..        ...       ...  ...  ...   ...  ...
395    normal    normal   no   no  good   no
396       NaN  abnormal  yes  yes  good   no
397       NaN       NaN  yes   no  poor   no
398  abnormal    normal  yes   no  good   no
399    normal    normal   no   no  good   no

[400 rows x 6 columns]

In [16]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy='constant',fill_value='Missing')
df4=imputer.fit_transform(df3)

In [17]:
dl2=pd.DataFrame(df4,columns=('rbc','pc','htn','dm','appet','pe'))

In [18]:
dl2.head()

rbc        pc  htn   dm appet   pe
0  Missing    normal  yes  yes  good   no
1  Missing    normal   no   no  good   no
2   normal    normal   no   no  good   no
3   normal    normal   no  yes  poor   no
4   normal  abnormal  yes   no  poor  yes

In [19]:
from sklearn.preprocessing import OrdinalEncoder
ordi=OrdinalEncoder()

In [20]:
dl3=ordi.fit_transform(dl2)

In [21]:
dl4=pd.DataFrame(dl3,columns=('rbc','pc','htn','dm','appet','pe'))

In [22]:
dl4

rbc   pc  htn   dm  appet   pe
0    0.0  2.0  2.0  2.0    1.0  2.0
1    0.0  2.0  1.0  1.0    1.0  2.0
2    2.0  2.0  1.0  1.0    1.0  2.0
3    2.0  2.0  1.0  2.0    3.0  2.0
4    2.0  1.0  2.0  1.0    3.0  3.0
..   ...  ...  ...  ...    ...  ...
395  2.0  2.0  1.0  1.0    1.0  2.0
396  0.0  1.0  2.0  2.0    1.0  2.0
397  0.0  0.0  2.0  1.0    3.0  2.0
398  1.0  2.0  2.0  1.0    1.0  2.0
399  2.0  2.0  1.0  1.0    1.0  2.0

[400 rows x 6 columns]

In [23]:
x=pd.concat([dl1,dl4],axis=1)

In [24]:
x

age          bp        sg        al        su         bgr     bu    sc  \
0    48.0   80.000000  1.020000  1.000000  0.000000  121.000000   36.0   1.2   
1     7.0   50.000000  1.020000  4.000000  0.000000  152.129316   18.0   0.8   
2    50.0   74.867666  1.020000  0.000000  0.000000   92.000000   19.0   1.2   
3    62.0   80.000000  1.010000  2.000000  3.000000  423.000000   53.0   1.8   
4    48.0   70.000000  1.005000  4.000000  0.000000  117.000000   56.0   3.8   
..    ...         ...       ...       ...       ...         ...    ...   ...   
395  38.0   60.000000  1.020000  0.000000  0.000000   91.000000   36.0   0.7   
396  64.0   90.000000  1.015000  3.000000  2.000000  463.000000   64.0   2.8   
397  48.0  100.000000  1.010276  2.182839  0.046629  103.000000   79.0   5.3   
398  48.0  110.000000  1.015000  3.000000  0.000000  106.000000  215.0  15.2   
399  40.0   80.000000  1.020000  0.000000  0.000000  119.000000   15.0   0.7   

            sod       pot       hemo       pcv         wbcc      rbcc  rbc  \
0    138.825303  3.818908  15.400000  44.00000  7800.000000  5.200000  0.0   
1    130.721286  3.892231  11.300000  38.00000  6000.000000  4.684685  0.0   
2    150.000000  4.800000  14.900000  48.00000  4700.000000  5.400000  2.0   
3    132.747426  4.966038   9.600000  31.00000  7500.000000  3.737033  2.0   
4    111.000000  2.500000  11.200000  32.00000  6700.000000  3.900000  2.0   
..          ...       ...        ...       ...          ...       ...  ...   
395  135.000000  3.700000  14.000000  46.00000  9100.000000  5.800000  2.0   
396  135.000000  4.100000  12.200000  40.00000  9800.000000  4.600000  0.0   
397  135.000000  6.300000   6.300000  19.00000  7200.000000  2.600000  0.0   
398  120.000000  5.700000   8.600000  26.00000  5000.000000  2.500000  1.0   
399  150.000000  4.900000  14.292961  43.88635  7928.161851  5.101035  2.0   

      pc  htn   dm  appet   pe  
0    2.0  2.0  2.0    1.0  2.0  
1    2.0  1.0  1.0    1.0  2.0  
2    2.0  1.0  1.0    1.0  2.0  
3    2.0  1.0  2.0    3.0  2.0  
4    1.0  2.0  1.0    3.0  3.0  
..   ...  ...  ...    ...  ...  
395  2.0  1.0  1.0    1.0  2.0  
396  1.0  2.0  2.0    1.0  2.0  
397  0.0  2.0  1.0    3.0  2.0  
398  2.0  2.0  1.0    1.0  2.0  
399  2.0  1.0  1.0    1.0  2.0  

[400 rows x 20 columns]

In [25]:
y=df['Label']

In [26]:
a=pd.concat([x,y],axis=1)

In [27]:
a

age          bp        sg        al        su         bgr     bu    sc  \
0    48.0   80.000000  1.020000  1.000000  0.000000  121.000000   36.0   1.2   
1     7.0   50.000000  1.020000  4.000000  0.000000  152.129316   18.0   0.8   
2    50.0   74.867666  1.020000  0.000000  0.000000   92.000000   19.0   1.2   
3    62.0   80.000000  1.010000  2.000000  3.000000  423.000000   53.0   1.8   
4    48.0   70.000000  1.005000  4.000000  0.000000  117.000000   56.0   3.8   
..    ...         ...       ...       ...       ...         ...    ...   ...   
395  38.0   60.000000  1.020000  0.000000  0.000000   91.000000   36.0   0.7   
396  64.0   90.000000  1.015000  3.000000  2.000000  463.000000   64.0   2.8   
397  48.0  100.000000  1.010276  2.182839  0.046629  103.000000   79.0   5.3   
398  48.0  110.000000  1.015000  3.000000  0.000000  106.000000  215.0  15.2   
399  40.0   80.000000  1.020000  0.000000  0.000000  119.000000   15.0   0.7   

            sod       pot  ...       pcv         wbcc      rbcc  rbc   pc  \
0    138.825303  3.818908  ...  44.00000  7800.000000  5.200000  0.0  2.0   
1    130.721286  3.892231  ...  38.00000  6000.000000  4.684685  0.0  2.0   
2    150.000000  4.800000  ...  48.00000  4700.000000  5.400000  2.0  2.0   
3    132.747426  4.966038  ...  31.00000  7500.000000  3.737033  2.0  2.0   
4    111.000000  2.500000  ...  32.00000  6700.000000  3.900000  2.0  1.0   
..          ...       ...  ...       ...          ...       ...  ...  ...   
395  135.000000  3.700000  ...  46.00000  9100.000000  5.800000  2.0  2.0   
396  135.000000  4.100000  ...  40.00000  9800.000000  4.600000  0.0  1.0   
397  135.000000  6.300000  ...  19.00000  7200.000000  2.600000  0.0  0.0   
398  120.000000  5.700000  ...  26.00000  5000.000000  2.500000  1.0  2.0   
399  150.000000  4.900000  ...  43.88635  7928.161851  5.101035  2.0  2.0   

     htn   dm  appet   pe   Label  
0    2.0  2.0    1.0  2.0     ckd  
1    1.0  1.0    1.0  2.0     ckd  
2    1.0  1.0    1.0  2.0  notckd  
3    1.0  2.0    3.0  2.0     ckd  
4    2.0  1.0    3.0  3.0     ckd  
..   ...  ...    ...  ...     ...  
395  1.0  1.0    1.0  2.0  notckd  
396  2.0  2.0    1.0  2.0     ckd  
397  2.0  1.0    3.0  2.0     ckd  
398  2.0  1.0    1.0  2.0     ckd  
399  1.0  1.0    1.0  2.0  notckd  

[400 rows x 21 columns]

In [28]:
#a=a.sort_values(['bu'],ascending=False)
#a.reset_index(drop=True,inplace=True)

In [29]:
#a.tail(40)

In [30]:
Label={'notckd':0,'ckd':1}
a['Label']=a['Label'].map(Label)

In [31]:
a.head(20)

age         bp     sg   al   su         bgr     bu    sc         sod  \
0   48.0  80.000000  1.020  1.0  0.0  121.000000   36.0   1.2  138.825303   
1    7.0  50.000000  1.020  4.0  0.0  152.129316   18.0   0.8  130.721286   
2   50.0  74.867666  1.020  0.0  0.0   92.000000   19.0   1.2  150.000000   
3   62.0  80.000000  1.010  2.0  3.0  423.000000   53.0   1.8  132.747426   
4   48.0  70.000000  1.005  4.0  0.0  117.000000   56.0   3.8  111.000000   
5   30.0  80.000000  1.020  0.0  0.0   89.000000   42.0   0.5  139.000000   
6   51.0  80.000000  1.010  2.0  0.0  106.000000   26.0   1.4  133.647830   
7   60.0  90.000000  1.015  3.0  0.0   74.000000   25.0   1.1  142.000000   
8   47.0  80.000000  1.025  0.0  0.0  124.000000   44.0   1.0  140.000000   
9   75.0  60.000000  1.020  0.0  0.0  110.000000   50.0   0.7  135.000000   
10  41.0  80.000000  1.020  0.0  0.0  122.000000   25.0   0.8  138.000000   
11  53.0  90.000000  1.020  2.0  0.0   70.000000  107.0   7.2  114.000000   
12  50.0  60.000000  1.010  2.0  4.0  490.000000   55.0   4.0  129.654816   
13  52.0  80.000000  1.020  0.0  0.0  128.000000   30.0   1.2  140.000000   
14  47.0  60.000000  1.020  0.0  0.0  137.000000   17.0   0.5  150.000000   
15  46.0  60.000000  1.020  0.0  0.0  102.000000   27.0   0.7  142.000000   
16  56.0  60.000000  1.025  0.0  0.0  132.000000   18.0   1.1  147.000000   
17  68.0  70.000000  1.010  0.0  0.0  100.000000   54.0  24.0  104.000000   
18  24.0  79.043223  1.015  2.0  4.0  410.000000   31.0   1.1  135.675311   
19  48.0  80.000000  1.025  0.0  0.0   75.000000   22.0   0.8  137.000000   

         pot  ...   pcv          wbcc      rbcc  rbc   pc  htn   dm  appet  \
0   3.818908  ...  44.0   7800.000000  5.200000  0.0  2.0  2.0  2.0    1.0   
1   3.892231  ...  38.0   6000.000000  4.684685  0.0  2.0  1.0  1.0    1.0   
2   4.800000  ...  48.0   4700.000000  5.400000  2.0  2.0  1.0  1.0    1.0   
3   4.966038  ...  31.0   7500.000000  3.737033  2.0  2.0  1.0  2.0    3.0   
4   2.500000  ...  32.0   6700.000000  3.900000  2.0  1.0  2.0  1.0    3.0   
5   5.000000  ...  52.0  10200.000000  5.000000  2.0  2.0  1.0  1.0    1.0   
6   3.406368  ...  35.0   7300.000000  4.600000  2.0  2.0  1.0  1.0    1.0   
7   3.200000  ...  39.0   7800.000000  4.400000  0.0  0.0  2.0  2.0    1.0   
8   4.900000  ...  41.0   7000.000000  5.700000  2.0  2.0  1.0  1.0    1.0   
9   5.000000  ...  40.0   8300.000000  5.800000  2.0  2.0  1.0  1.0    0.0   
10  5.000000  ...  41.0   9100.000000  5.200000  2.0  2.0  1.0  1.0    1.0   
11  3.700000  ...  29.0  12100.000000  3.700000  1.0  1.0  2.0  2.0    3.0   
12  5.303809  ...  28.0  10101.651324  3.563175  0.0  1.0  2.0  2.0    1.0   
13  4.500000  ...  52.0   4300.000000  5.700000  2.0  2.0  1.0  1.0    1.0   
14  3.500000  ...  44.0   7900.000000  4.500000  2.0  2.0  1.0  1.0    1.0   
15  4.900000  ...  44.0  11000.000000  5.400000  2.0  2.0  1.0  1.0    1.0   
16  4.700000  ...  45.0   7500.000000  5.600000  2.0  2.0  1.0  1.0    1.0   
17  4.000000  ...  36.0   5473.550467  4.174756  0.0  2.0  1.0  1.0    1.0   
18  5.506120  ...  44.0   6900.000000  5.000000  2.0  1.0  1.0  2.0    1.0   
19  5.000000  ...  51.0   6000.000000  6.500000  2.0  2.0  1.0  1.0    1.0   

     pe  Label  
0   2.0      1  
1   2.0      1  
2   2.0      0  
3   2.0      1  
4   3.0      1  
5   2.0      0  
6   2.0      1  
7   3.0      1  
8   2.0      0  
9   0.0      0  
10  2.0      0  
11  2.0      1  
12  2.0      1  
13  2.0      0  
14  2.0      0  
15  2.0      0  
16  2.0      0  
17  2.0      1  
18  3.0      1  
19  2.0      0  

[20 rows x 21 columns]

In [32]:
u=a.iloc[:,:-1]
v=a['Label']

In [33]:
from imblearn.over_sampling import SMOTE
from imblearn.over_sampling import SVMSMOTE 

In [34]:
smote=SMOTE()
sm = SVMSMOTE()

In [35]:
x_train_resample,y_train_resample=sm.fit_resample(u,v) 

In [36]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
k=scaler.fit_transform(x_train_resample)

In [37]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(k,y_train_resample,test_size=0.2, random_state=0)

In [38]:
from sklearn.model_selection import KFold
from sklearn.model_selection import ShuffleSplit
fold=ShuffleSplit(n_splits=5, test_size=0.1, random_state=0)
fold1=KFold(5)
from sklearn.model_selection import cross_val_score

In [39]:
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

In [40]:
svm=SVC(C=100)
knn=KNeighborsClassifier(n_neighbors=1,weights= 'uniform',metric='manhattan')
gdb=GradientBoostingClassifier(n_estimators=100,max_depth=7,learning_rate=0.1,min_samples_leaf=4)
lgb=LGBMClassifier(n_estimators=100,max_depth=7,learning_rate=0.1,min_child_weight=5)
xgb=XGBClassifier(n_estimators=500,max_depth=5,learning_rate=0.2,min_child_weight=3,eval_metric='error')

In [41]:
labels=['svm','knn','gdb','xgb','lgb']

In [42]:
for clf,label in zip([svm,knn,gdb,xgb,lgb],labels):
    training_start = time.perf_counter()
    results_svm=cross_val_score(clf,x_train,y_train,cv=fold,scoring='accuracy')
    training_end = time.perf_counter()
    train_time = training_end-training_start
    print("Time consumed for training: %4.3f seconds" % (train_time))
    print("%0.4faccuracy with a standard deviation of %0.4f" % (results_svm.mean(), results_svm.std()),label)

Time consumed for training: 0.042 seconds
1.0000accuracy with a standard deviation of 0.0000 svm
Time consumed for training: 0.035 seconds
0.9950accuracy with a standard deviation of 0.0100 knn
Time consumed for training: 2.541 seconds
0.9950accuracy with a standard deviation of 0.0100 gdb


C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgbo

Time consumed for training: 1.809 seconds
0.9900accuracy with a standard deviation of 0.0122 xgb
Time consumed for training: 0.263 seconds
0.9850accuracy with a standard deviation of 0.0122 lgb


In [43]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score 

In [44]:
for clf,label in zip([svm,knn,gdb,xgb,lgb],labels):
    training_start = time.perf_counter()
    clf.fit(x_train,y_train)
    training_end = time.perf_counter()
    train_time = training_end-training_start
    print("Time consumed for training: %4.3f seconds" % (train_time))
    y_pred=clf.predict(x_test)
    print(accuracy_score(y_test,y_pred),label)
    print(confusion_matrix(y_test,y_pred))
    print(precision_score(y_test,y_pred))
    print(recall_score(y_test,y_pred))
    print(f1_score(y_test,y_pred))
    print(roc_auc_score(y_test,y_pred))
        

Time consumed for training: 0.006 seconds
1.0 svm
[[45  0]
 [ 0 55]]
1.0
1.0
1.0
1.0
Time consumed for training: 0.001 seconds
0.99 knn
[[45  0]
 [ 1 54]]
1.0
0.9818181818181818
0.9908256880733944
0.990909090909091
Time consumed for training: 0.527 seconds
1.0 gdb
[[45  0]
 [ 0 55]]
1.0
1.0
1.0
1.0


C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


Time consumed for training: 0.343 seconds
1.0 xgb
[[45  0]
 [ 0 55]]
1.0
1.0
1.0
1.0
Time consumed for training: 0.037 seconds
1.0 lgb
[[45  0]
 [ 0 55]]
1.0
1.0
1.0
1.0


In [45]:
from mlxtend.evaluate import combined_ftest_5x2cv

In [46]:
f, p = combined_ftest_5x2cv(estimator1=xgb,
                            estimator2=lgb,
                            X=k, y=y_train_resample,
                            random_seed=1)

C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgboost\sklearn.py:1146: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
C:\Users\Md.Mustafizur Rahman\anaconda3\lib\site-packages\xgbo

In [47]:
print('F statistic: %.3f' % f)
print('p value: %.3f' % p)

F statistic: 1.000
p value: 0.535
